#!/bin/bash

# Assuming $CFILE contains the name of the C file
CFILE="main.c"

# Get the base name of the C file without the extension
BASE_NAME=$(basename "$CFILE" .c)

# Compile the C file without linking
gcc -c "$CFILE" -o "${BASE_NAME}.o"

